// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

namespace StudentAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentAPI.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "64a40c33-a4c3-443b-9744-3c738d53ef14",
                            City = "London",
                            Email = "tom@gmail.com",
                            Employer = "Google",
                            FirstName = "Tom",
                            LastName = "Day",
                            MobileNumber = "1234567890",
                            Province = "Ontario",
                            Specialization = "Science"
                        },
                        new
                        {
                            StudentId = "fcf18638-e817-4192-ba0e-aae646088a09",
                            City = "Vancouver",
                            Email = "john@gmail.com",
                            Employer = "Apple",
                            FirstName = "John",
                            LastName = "Doe",
                            MobileNumber = "1234567890",
                            Province = "British Columbia",
                            Specialization = "Engineering"
                        },
                        new
                        {
                            StudentId = "045538b7-5763-4c6e-81ec-fbe270801c65",
                            City = "Toronto",
                            Email = "jane@gmail.com",
                            Employer = "Microsoft",
                            FirstName = "Jane",
                            LastName = "Doe",
                            MobileNumber = "1234567890",
                            Province = "Ontario",
                            Specialization = "Engineering"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
